export const GET_POSTS = 'GET_POSTS'
export const GET_CURRENT_POST = 'GET_CURRENT_POST'

export const ADD_NEW_POST = 'ADD_NEW_POST'
export const UPDATE_NEW_POST_BODY = 'UPDATE_NEW_POST_BODY'
export const UPDATE_NEW_POST_TITLE = 'UPDATE_NEW_POST_TITLE'